"""Profession and class trainer rumors.

Trainers are listed per faction and per race of the player they are meant
for, so a trainer may appear under several races and need not be of that
race. Every name is a spawned NPC with the trainer flag in acore_world
(checked against creature_template and creature). Level bands: the
defaults of the LLMChatter.ThemedTopics.*RumorFullLevel / *MaxLevel keys.
"""

PROFESSION_RUMOR_LEVELS = (20, 30)
CLASS_TRAINER_RUMOR_LEVELS = (15, 25)

PROFESSION_ABILITIES = {
    'Alchemy': [
        "An alchemist can turn ordinary herbs into a potion that restores one's strength within a few seconds after a hard fight",
        "Alchemists can brew elixirs that make a person stronger, faster, or hardier for several hours",
        "Alchemists can brew potions that let one briefly see through illusions and detect what the ordinary eye does not notice",
        "Alchemists can brew potions that let one see the dead, whom other living beings do not notice",
        "Alchemists can brew an elixir that allows one to breathe underwater",
        "An alchemist can prepare a potion that turns a person into a completely different creature",
        "Alchemists can create infusions that let even a naked warrior without armor withstand a dragon's breath",
        "Alchemists can create infusions that let even a naked warrior without armor bathe in the icy waters of Northrend without freezing",
        "Alchemists can prepare a potion that lets one become invisible for a short time",
        "Alchemists can create stones that turn ordinary metals into more valuable ones",
        "Alchemists know the secret of creating the Philosopher's Stone, a tool needed for the most unusual transmutations",
        "Alchemists know the properties of herbs so well that they can judge their quality by smell alone",
        "Alchemists can prepare a potion that causes strange visions",
        "Alchemists can prepare a poison, a single drop of which is enough to kill even an ogre",
    ],
    'Blacksmithing': [
        "Blacksmiths can create weapons that will outlast several generations of their owners",
        "Blacksmiths can forge swords capable of withstanding a clash with the weapons of huge monsters",
        "Blacksmiths can set precious stones and magical gems into weapons",
        "Blacksmiths create armor fitted so well to its owner that it barely hinders movement",
        "Blacksmiths can make weapons of almost any shape, from a huge war hammer to the finest blade",
        "Blacksmiths can create metal tips and parts that greatly strengthen ordinary weapons",
        "Blacksmiths can work with unusual metals that an ordinary forge simply could not withstand",
        "Blacksmiths can judge the quality of ore by the sound alone that a piece of metal makes when it falls on the anvil",
        "Blacksmiths say that most warriors wear terrible, useless armor, but cannot notice its uselessness without the right knowledge",
        "Blacksmiths say that most heroes who fell in battle died because of poor-quality armor that they failed to recognize in time",
        "Blacksmiths make not only weapons, but also metal parts for engineers, alchemists, and other craftsmen",
        "Blacksmiths can restore almost any broken blade, including ancient forgotten artifacts, as long as at least a few large fragments of it remain",
        "Blacksmiths say that a good hammer and the right fire matter more than expensive metal",
        "Blacksmiths used to create weapons so beautiful that they were bought as works of art, without the blade ever being drawn",
    ],
    'Enchanting': [
        "Enchanters can turn a completely ordinary item into a magical relic",
        "Enchanters can enchant a weapon so that it glows with fire, frost, or another magical energy",
        "Enchanters can imbue cloaks, gloves, boots, and other items with unusual properties",
        "Enchanters can extract the magical power from an old item and transfer it to another",
        "Enchanters know why some old items leave magical crystals behind after being destroyed",
        "Enchanters can make a weapon noticeably faster, or heavier for the enemy, while keeping it light for its wielder",
        "Enchanters can enchant even the simplest item, and no one but a knowledgeable enchanter will notice the difference at first glance",
        "Enchanters can create some enchantments so subtle that they cannot be seen, yet the owner immediately feels the difference",
        "Enchanters can enchant their own shoes so that the shoes slip onto their feet by themselves when they get out of bed",
        "Enchanters can enchant a broom so that it sweeps by itself",
        "Enchanters can turn a set of stones or pieces of metal into an intelligent and obedient golem",
        "Enchanters claim that every magical item holds a part of its creator's story",
        "Enchanters can break down old relics to obtain rare magical reagents",
        "Enchanters can cast enchantments that will outlive the item's first owner",
    ],
    'Engineering': [
        "Engineers can make a device for almost any problem; the only question is how big the explosion will be",
        "Engineers create mechanical pets that look almost like real animals",
        "Engineers create miniature devices capable of repairing armor right in the middle of a journey",
        "Engineers can put together a contraption that lets one move quickly, jump, or escape from a great height",
        "Engineers can create mechanical devices that can help revive a fallen comrade without any healers",
        "Engineers make special goggles capable of detecting invisible things and creatures",
        "Engineers can create a device that greatly increases one's range of vision",
        "Engineers create small robots capable of fighting in place of their master",
        "Engineers can turn ordinary explosives into real siege devices",
        "Engineers can make, out of a few pieces of metal and a couple of gears, a device unlike anything else in the world",
        "Engineers create weapon attachments, rockets, bombs, and grenades",
        "Engineers create devices that let one briefly pretend to be another creature",
        "Engineers can create almost anything they can imagine, but rarely on the first try",
    ],
    'Inscription': [
        "Scribes can capture a magical property in a few lines of text",
        "Scribes create glyphs that change the way spells work",
        "Some scribes can create glyphs and scrolls of immense magical power, while other scribes only draw pictures of naked elves",
        "Scribes can create scrolls that let an ordinary person temporarily use magical abilities",
        "Scribes can create enhancement scrolls that are useful even to those who do not wield magic",
        "Scribes know how the right combination of inks and symbols can make a spell much more effective",
        "Scribes create special magical cards that are valuable artifacts in their own right",
        "Scribes can create special books and tomes for storing magical knowledge",
        "Scribes say that old mages are willing to pay huge sums of money for rare symbols and high-quality magical inks",
        "Scribes can copy a complex magical symbol after seeing it only once",
        "Scribes speak of glyphs that look completely meaningless to the uninitiated, but change the power of the spells of those who know how to read them",
    ],
    'Jewelcrafting': [
        "Jewelcrafters can see the value of a rough stone where others see only an ordinary piece of rock",
        "Jewelcrafters can cut gems so that they shine brighter than magical crystals",
        "Jewelcrafters speak of gems that can enhance certain qualities of their owner",
        "Jewelcrafters can set a stone into a weapon or armor so that it becomes part of a magical structure",
        "Jewelcrafters say that some gems have properties that cannot be noticed until they are properly cut",
        "Jewelcrafters can create rings and necklaces that are worth a fortune even before they are enchanted",
        "Jewelcrafters can find rare stones where an inexperienced prospector would walk right past",
        "Jewelcrafters speak of stones so rare that a single good specimen can provide for a craftsman for life",
        "Jewelcrafters say that a properly cut stone can look completely different in daylight, in moonlight, and under magical light",
        "Jewelcrafters can match a gem to a specific owner so that the owner gets the greatest benefit from it",
        "Jewelcrafters make jewelry that becomes family heirlooms and is passed down through dozens of generations",
        "Jewelcrafters relate that a single especially rare stone can turn out to be worth more than a whole cartload of gold",
        "Jewelcrafters say that the right magical stone can grant magical abilities even to someone who was born without them",
    ],
    'Leatherworking': [
        "Leatherworkers can make light armor from the hide of a wild beast that is almost as good as metal armor",
        "Leatherworkers can work even the hides of the most dangerous creatures of Azeroth",
        "Leatherworkers speak of leather armor so flexible that it lets its wearer move almost silently",
        "Leatherworkers can turn a rough hide into soft, expensive leather",
        "Leatherworkers make belts, bags, quivers, drums, and many other useful things",
        "Leatherworkers can work with very rare kinds of leather that cannot be worked with ordinary tools",
        "Leatherworkers create hides and cloaks that can withstand magical effects and that make a fight against a mage trivial",
        "Leatherworkers can tell which creature a hide belonged to just by touching it",
        "Leatherworkers can almost completely hide the traces of damage on a hide while turning it into armor",
        "Leatherworkers say that some leather goods are made so skillfully that they are mistaken for the work of the finest tailors",
        "Leatherworkers can make sturdy armor from materials that an ordinary person would consider useless",
        "Leatherworkers can turn scales into sturdy mail",
    ],
    'Tailoring': [
        "Tailors can turn ordinary cloth into clothing capable of withstanding magical effects",
        "Tailors create cloaks that look completely ordinary but have magical properties",
        "Tailors speak of fabrics that weigh almost nothing and yet withstand serious damage",
        "Tailors can create clothing perfectly fitted to a specific owner",
        "Tailors can embroider magical patterns and runes on cloth",
        "Tailors can create bags that are much roomier inside than they look from the outside",
        "Tailors work with rare fabrics that an ordinary needle simply cannot pierce",
        "Tailors create outfits so beautiful that people are willing to pay more for them than for good armor",
        "Tailors tell of cloaks that help their wearer become invisible",
        "Tailors can tell from a single scrap of cloth where and how it was made",
        "Tailors can create true works of art using only a needle, thread, and a few simple materials",
    ],
    'Herbalism': [
        "Herbalists can find a rare plant where another person would see only ordinary grass",
        "Herbalists can find expensive and valuable plants among ordinary grass",
        "Herbalists find herbs with properties so potent that a single leaf of them is enough for an alchemical potion",
        "Herbalists know which herb can be made into a healing brew and which into a terrible poison",
        "Herbalists know of plants that bloom for only a few minutes a year",
        "Herbalists speak of herbs that grow only in total darkness",
        "Herbalists speak of herbs that grow only in complete silence",
        "Herbalists know of plants that react to touch and close up before anyone can pick them",
        "Herbalists can determine the healing properties of an unknown plant almost instantly",
        "Herbalists can find plants that restore strength, stop bleeding, or protect against poison",
        "Herbalists say that some rare herbs are so valuable that alchemists are willing to pay more for them than for gold",
        "Herbalists speak of plants that cannot be seen with ordinary sight",
        "Herbalists know old ways of preserving an herb so that it keeps its magical properties for years",
        "Herbalists know which part of a plant to cut so that it keeps on growing",
        "Herbalists can tell a useful herb from a poisonous one by its scent before they even pick it",
        "Herbalists tell of a special flower that blooms only atop the highest mountains",
    ],
    'Mining': [
        "Miners can detect ore simply by tapping on a stone wall",
        "Miners can find veins of metal where dozens of other miners noticed nothing",
        "Miners know of rare metals found only in the deepest caves",
        "Miners can extract ore without destroying the whole vein",
        "Miners say that some deposits are so rich that a single lucky find can change a miner's fortune",
        "Miners say that in the depths of Azeroth one can find metals that will not melt in an ordinary forge",
        "Miners speak of ores that glow in the dark or react to magic",
        "Miners have found gems right inside a vein of metal",
        "Miners tell of mines where the walls are completely covered in rare gemstones",
        "Miners can judge the quality of a metal before they even extract it from the stone",
        "Sometimes, instead of ore, miners find something more valuable in the rock, such as a fossil or a precious artifact",
        "Miners say that the greatest treasure of a mine is sometimes not the metal they were looking for at all",
    ],
    'Skinning': [
        "Skinners can skin a huge beast so that its hide stays almost completely intact",
        "Skinners know which body parts of rare creatures are especially prized by leatherworkers",
        "Skinners say that if you don't skin the carcass of a slain animal, you lose more than half of what the hunt could earn you",
        "Skinners say that leaving a slain animal unskinned is like leaving a treasure to rot in the sun",
        "Skinners say that some monsters yield materials that look nothing like ordinary leather",
        "Skinners can quickly tell how valuable a carcass is",
        "Skinners say that some beasts leave behind hides that can be used to make unusual armor",
        "Skinners say that the scales of some creatures are worth more than a good weapon",
        "Skinners can harvest materials even from a very thick-skinned or armored creature",
        "Skinners say that some hides retain the unusual or magical properties of the beast itself",
        "Skinners speak of special scales that let almost no fire through",
        "Skinners speak of hides that, when properly treated, become lighter than cloth yet stronger than metal",
    ],
    'Fishing': [
        "Fishermen say that some waters are home to fish that no one has ever managed to catch twice",
        "Fishermen have found gems and other treasures in the bellies of fish",
        "Fishermen speak of fish that glow in the dark",
        "Fishermen speak of fish with such unusual properties that alchemists are willing to pay a lot of money for them",
        "Fishermen claim that from deep water you can pull up not only fish, but also old weapons, chests, and even magical items",
        "Fishermen can tell which bait is needed before the very first cast",
        "Fishermen say that some rare fish appear only at certain times of day",
        "Fishermen tell of fish that can be caught only in certain weather",
        "Fishermen speak of giant fish capable of dragging an inexperienced fisherman into the water",
        "Some fishermen spend their whole lives searching for a single legendary fish",
        "Fishermen can sit perfectly still for hours and still notice the slightest twitch of the bobber",
        "Fishermen say that the most interesting catch is not a fish at all, it's whatever snags on the hook at the bottom",
        "A fisherman once pulled a powerful enchanted sword from the bottom of a river",
    ],
    'First Aid': [
        "Medics can stop bleeding in a matter of seconds using nothing but bandages, without any magic at all",
        "Medics can bring a fighter who only a moment ago seemed mortally wounded back to their senses",
        "Medics speak of special bandages made from cloth of such quality that they work almost like magical healing",
        "Medics know when a wound needs to be bandaged and when any movement will only make things worse",
        "Medics can treat burns, cuts, and other battle wounds without a single spell",
        "Medics can provide aid even in the middle of a battlefield",
        "Medics use special remedies that make bandaging far more effective",
        "Medics tell of warriors who survived grievous wounds only because a skilled medic happened to be nearby",
        "Medics say that first aid is the one craft that anyone might need someday, regardless of class",
        "Medics can tell from the look of a wound what weapon inflicted it",
    ],
    'Cooking': [
        "Cooks can prepare a dish after which a warrior feels as if they had just rested for an entire day",
        "Cooks say that some dishes are so filling that even a small portion satisfies hunger for a long time",
        "Cooks tell of recipes for food that increases strength, agility, or stamina",
        "Cooks tell of dishes so delicious that army generals surrendered cities to the enemy just to taste one more bite",
        "Cooks know how to use the meat of rare beasts that an ordinary person wouldn't even dare to taste",
        "Cooks tell of a fish of which one small piece of meat is incredibly delicious, while all the rest is deadly poisonous",
        "Cooks say that some dishes gain unusual properties thanks to special spices and herbs",
        "Cooks can make an edible dish out of practically anything, as long as they have the right spices on hand",
        "Cooks say that a drop of poison in food has often killed those whom neither sword nor magic could touch, so it pays to be friends with your cook and treat them with respect",
        "Cooks speak of special recipes that are passed down from generation to generation and kept as family secrets",
        "Cooks speak of dishes so spicy that even an orc asks for water afterward",
        "Cooks say that a good cook can prepare both refined elven dishes and spicy, well-charred orcish ones",
        "Cooks can tell from a single bite which people's cuisine a dish comes from",
        "Cooks can prepare exotic dishes from fish that an ordinary fisherman considers too strange to eat",
        "Cooks demand ingredients so rare that preparing their dishes turns into a true adventure in itself",
        "Cooks prepare dishes that help you recover right on the road, without wasting time on a long rest",
        "Cooks can make an excellent dinner even from ingredients that someone else would consider spoiled or useless",
        "Cooks tell of special dishes valued not for their benefits but for their taste: they are made especially for holidays, feasts, and important gatherings",
        "Cooks can feed an entire group from a single pot of food",
        "Cooks know the secrets of preparing food that stays fresh much longer than usual",
        "Cooks say that every race has a dish that an outsider can never prepare properly: there are too many little traditions, secrets, and right ways of cutting",
        "Cooks know that boar meat, fish, and mushrooms are not yet a dinner. Dinner begins with the spices",
        "Cooks say that some travelers seek out taverns where a famous cook works just to taste their signature dish",
        "Cooks can make food so delicious that even the gloomiest mercenaries stop arguing for a while",
        "Cooks can tell from a single bite what creature was used as an ingredient, what it was fed, and how long ago it was caught",
        "Cooks say that the best way to befriend an enemy is to cook them a delicious meal",
    ],
}


def _t(skill, name, place):
    return {'skill': skill, 'name': name, 'place': place}


_IRONFORGE_PROFESSIONS = [
    _t('Blacksmithing', 'Tognus Flintfire', 'Kharanos, Dun Morogh'),
    _t('Mining', 'Yarr Hammerstone', 'Kharanos, Dun Morogh'),
    _t('Engineering', 'Bronk Guzzlegear', 'Kharanos, Dun Morogh'),
    _t('Alchemy', 'Tally Berryfizz', 'Tinker Town in Ironforge'),
    _t('Herbalism', 'Reyna Stonebranch', 'The Great Forge in Ironforge'),
    _t('Leatherworking', 'Tognus Flintfire', 'Kharanos, Dun Morogh'),
    _t('Skinning', 'Balthus Stoneflayer', 'The Great Forge in Ironforge'),
    _t('Tailoring', 'Jormund Stonebrow', 'The Great Forge in Ironforge'),
    _t('Enchanting', 'Gimble Thistlefuzz', 'Ironforge'),
    _t('Cooking', 'Gremlock Pilsnor', 'Kharanos, Dun Morogh'),
    _t('Fishing', 'Grimnur Stonebrand', 'The Forlorn Cavern in Ironforge'),
    _t('First Aid', 'Nissa Firestone', 'Ironforge'),
    _t('Inscription', 'Elise Brightletter', 'Tinker Town in Ironforge'),
    _t('Jewelcrafting', 'Farii', 'The Crystal Hall in the Exodar'),
]

_ORGRIMMAR_PROFESSIONS = [
    _t('Alchemy', "Miao'zan", "Sen'jin Village, Durotar"),
    _t('Blacksmithing', 'Dwukk', 'Razor Hill, Durotar'),
    _t('Enchanting', 'Godan', 'The Drag in Orgrimmar'),
    _t('Engineering', 'Roxxik', 'Valley of Honor in Orgrimmar'),
    _t('Inscription', "Jo'mah", 'The Drag in Orgrimmar'),
    _t('Leatherworking', 'Karolek', 'The Drag in Orgrimmar'),
    _t('Tailoring', 'Magar', 'The Drag in Orgrimmar'),
    _t('Herbalism', 'Mishiki', "Sen'jin Village, Durotar"),
    _t('Mining', 'Krunn', 'Razor Hill, Durotar'),
    _t('Skinning', 'Thuwd', 'The Drag in Orgrimmar'),
    _t('Cooking', 'Zamja', 'The Drag in Orgrimmar'),
    _t('Fishing', "Lau'Tiki", "south of Sen'jin Village, Durotar"),
]

_KALINDA = _t('Jewelcrafting', 'Kalinda',
              'the Royal Exchange in Silvermoon City')

PROFESSION_TRAINERS = {
    'Alliance': {
        'Human': [
            _t('Alchemy', 'Alchemist Mallory', 'a house in the hills north of Northshire'),
            _t('Herbalism', 'Herbalist Pomeroy', 'a house in the hills north of Northshire'),
            _t('Blacksmithing', 'Smith Argus', 'Goldshire, Elwynn Forest'),
            _t('Mining', 'Gelman Stonehand', 'the Dwarven District of Stormwind'),
            _t('Leatherworking', 'Adele Fielder', 'a house on the shore of Crystal Lake, east of Goldshire'),
            _t('Skinning', 'Helene Peltskinner', 'a house on the shore of Crystal Lake, east of Goldshire'),
            _t('Inscription', 'Catarina Stanford', 'the Mage Quarter of Stormwind'),
            _t('Tailoring', 'Eldrin', 'Eastvale Logging Camp, Elwynn Forest'),
            _t('Enchanting', 'Kitta Firewind', 'the Tower of Azora, Elwynn Forest'),
            _t('Engineering', 'Lilliam Sparkspindle', 'the Dwarven District of Stormwind'),
            _t('Cooking', 'Tomas', 'Goldshire, Elwynn Forest'),
            _t('Fishing', 'Lee Brown', 'Crystal Lake, east of Goldshire'),
            _t('First Aid', 'Michelle Belle', 'Goldshire, Elwynn Forest'),
            _t('Jewelcrafting', 'Farii', 'The Crystal Hall in the Exodar'),
        ],
        'Dwarf': list(_IRONFORGE_PROFESSIONS),
        'Gnome': list(_IRONFORGE_PROFESSIONS),
        'Night Elf': [
            _t('Alchemy', 'Cyndra Kindwhisper', 'Dolanaar, Teldrassil'),
            _t('Blacksmithing', 'Delfrum Flintbeard', 'Auberdine, Darkshore'),
            _t('Enchanting', 'Taladan', "the Craftsmen's Terrace in Darnassus"),
            _t('Engineering', 'Jenna Lemkenilli', 'Auberdine, Darkshore'),
            _t('Inscription', 'Feyden Darkin', "the Craftsmen's Terrace in Darnassus"),
            _t('Leatherworking', 'Nadyia Maneweaver', 'Teldrassil'),
            _t('Tailoring', "Me'lynn", "the Craftsmen's Terrace in Darnassus"),
            _t('Herbalism', 'Firodren Mooncaller', 'the Temple Gardens in Darnassus'),
            _t('Mining', 'Kurdram Stonehammer', 'Auberdine, Darkshore'),
            _t('Skinning', 'Eladriel', "the Craftsmen's Terrace in Darnassus"),
            _t('Cooking', 'Zarrin', 'Dolanaar, Teldrassil'),
            _t('Fishing', 'Androl Oakhand', "Rut'theran Village, Teldrassil"),
            _t('First Aid', 'Byancie', 'Dolanaar, Teldrassil'),
            _t('Jewelcrafting', 'Farii', 'The Crystal Hall in the Exodar'),
        ],
        'Draenei': [
            _t('Alchemy', 'Lucc', 'the Vault of Lights in the Exodar'),
            _t('Blacksmithing', 'Miall', "the Traders' Tier in the Exodar"),
            _t('Enchanting', 'Nahogg', 'The Crystal Hall in the Exodar'),
            _t('Engineering', 'Ockil', "the Traders' Tier in the Exodar"),
            _t('Inscription', 'Thoth', 'The Crystal Hall in the Exodar'),
            _t('Leatherworking', 'Akham', "the Traders' Tier in the Exodar"),
            _t('Tailoring', 'Refik', "the Traders' Tier in the Exodar"),
            _t('Herbalism', 'Heur', 'Azure Watch, Azuremyst Isle'),
            _t('Mining', 'Dulvi', 'Azure Watch, Azuremyst Isle'),
            _t('Skinning', 'Gurf', 'Stillpine Hold, Azuremyst Isle'),
            _t('Cooking', '"Cookie" McWeaksauce', "Odesyus' Landing, Azuremyst Isle"),
            _t('Fishing', 'Diktynna', 'just outside Ammen Vale, Azuremyst Isle'),
            _t('First Aid', 'Nus', 'The Crystal Hall in the Exodar'),
            _t('Jewelcrafting', 'Farii', 'The Crystal Hall in the Exodar'),
        ],
    },
    'Horde': {
        'Orc': _ORGRIMMAR_PROFESSIONS + [
            _t('First Aid', 'Arnok', 'the Valley of Spirits in Orgrimmar'),
            _KALINDA,
        ],
        'Troll': _ORGRIMMAR_PROFESSIONS + [
            _t('First Aid', 'Rawrk', 'Razor Hill, Durotar'),
            _KALINDA,
        ],
        'Tauren': [
            _t('Alchemy', 'Bena Winterhoof', 'the Middle Rise in Thunder Bluff'),
            _t('Blacksmithing', 'Karn Stonehoof', 'Thunder Bluff'),
            _t('Enchanting', 'Teg Dawnstrider', 'Thunder Bluff'),
            _t('Engineering', 'Roxxik', 'Valley of Honor in Orgrimmar'),
            _t('Inscription', 'Poshken Hardbinder', 'Spirit Rise in Thunder Bluff'),
            _t('Leatherworking', 'Chaw Stronghide', 'Bloodhoof Village, Mulgore'),
            _t('Tailoring', 'Tepa', 'the central bluff in Thunder Bluff'),
            _t('Herbalism', 'Komin Winterhoof', 'the central bluff in Thunder Bluff'),
            _t('Mining', 'Brek Stonehoof', 'the central bluff in Thunder Bluff'),
            _t('Skinning', 'Yonn Deepcut', 'Bloodhoof Village, Mulgore'),
            _t('Cooking', 'Pyall Silentstride', 'Bloodhoof Village, Mulgore'),
            _t('Fishing', 'Kah Mistrunner', 'the Middle Rise in Thunder Bluff'),
            _t('First Aid', 'Pand Stonebinder', 'Spirit Rise in Thunder Bluff'),
            _KALINDA,
        ],
        'Undead': [
            _t('Alchemy', 'Carolai Anise', 'Brill, Tirisfal Glades'),
            _t('Blacksmithing', 'James Van Brunt', 'the War Quarter of the Undercity'),
            _t('Enchanting', 'Lavinia Crowe', 'the Undercity'),
            _t('Engineering', 'Franklin Lloyd', 'the Undercity'),
            _t('Inscription', 'Margaux Parchley', 'the Apothecarium in the Undercity'),
            _t('Leatherworking', 'Shelene Rhobart', "Death's Watch Waystation, Tirisfal Glades"),
            _t('Tailoring', 'Josef Gregorian', 'the Undercity'),
            _t('Herbalism', 'Martha Alliestar', 'the Apothecarium in the Undercity'),
            _t('Mining', 'Brom Killian', 'the War Quarter of the Undercity'),
            _t('Skinning', 'Killian Hagey', "the Rogues' Quarter of the Undercity"),
            _t('Cooking', 'Eunice Burch', 'the Undercity'),
            _t('Fishing', 'Clyde Kellen', 'Brightwater Lake, Tirisfal Glades'),
            _t('First Aid', 'Nurse Neela', 'Brill, Tirisfal Glades'),
            _KALINDA,
        ],
        'Blood Elf': [
            _t('Alchemy', 'Camberon', 'the Court of the Sun in Silvermoon City'),
            _t('Blacksmithing', 'Bemarrin', "Farstriders' Square in Silvermoon City"),
            _t('Enchanting', 'Sedana', 'the Court of the Sun in Silvermoon City'),
            _t('Engineering', 'Danwe', "Farstriders' Square in Silvermoon City"),
            _t('Inscription', 'Zantasia', 'the Court of the Sun in Silvermoon City'),
            _t('Leatherworking', 'Lynalis', 'the Walk of Elders in Silvermoon City'),
            _t('Tailoring', 'Keelen Sheets', 'the Bazaar in Silvermoon City'),
            _t('Herbalism', 'Botanist Tyniarrel', "Saltheril's Haven, Eversong Woods"),
            _t('Mining', 'Belil', "Farstriders' Square in Silvermoon City"),
            _t('Skinning', 'Tyn', 'the Walk of Elders in Silvermoon City'),
            _t('Cooking', 'Quarelestra', 'the Falconwing Inn, Falconwing Square, Eversong Woods'),
            _t('Fishing', 'Drathen', 'the Walk of Elders in Silvermoon City'),
            _t('First Aid', 'Alestus', 'the Walk of Elders in Silvermoon City'),
            _KALINDA,
        ],
    },
}

CLASS_ABILITIES = {
    'Warrior': [
        "Warriors are so skilled with a shield that they can withstand a blow that would knock an ordinary person off their feet",
        "Warriors can split a shield in half with a single blow of a two-handed weapon",
        "Warriors can fight with two two-handed swords at the same time",
        "Warriors know how to turn an opponent's rage against them",
        "Warriors can tell an opponent's fighting style by the way they hold the hilt",
        "Warriors can throw a weapon with such force that it knocks the enemy off their feet",
        "Warriors know how to make an opponent attack them specifically, thereby protecting their comrades",
        "Warriors can keep fighting even after wounds from which another person could no longer get up",
        "Warriors can make several enemies stagger with a single powerful blow to the ground",
        "Warriors know many ways to disarm an opponent without killing them",
        "Warriors know that sometimes the best shield protects not against the sword, but against the fear of it",
        "Warriors are so used to battle that they can tell by the sound of a blow how sturdy an opponent's armor is",
    ],
    'Mage': [
        "Mages can create a portal to almost any known place",
        "Mages can summon water and food literally out of thin air",
        "Mages can turn an enemy into a harmless animal",
        "Mages can freeze an opponent so quickly that they won't have time to take a single step",
        "Mages can call down a real rain of fire",
        "Mages can create an ice barrier around themselves that will withstand many blows without cracking",
        "Mages can become invisible and slip past entire groups of enemies",
        "Mages can teleport an entire group of people",
        "Mages can open a portal to their home and return there in a matter of seconds",
        "Mages can create magical copies of themselves",
        "Mages can stop time for an opponent",
        "Mages study spells that let them move so fast it is as if distance didn't exist at all",
    ],
    'Hunter': [
        "A hunter can tame almost any wild creature if they know the right approach",
        "Hunters travel with pets that were once deadly predators",
        "Hunters are such good marksmen that they can hit a coin from a huge distance",
        "Hunters can track a person by a single footprint, a broken twig, or a tuft of fur",
        "Hunters know how to set traps so that the prey notices them only when it is already too late",
        "Hunters know how to use special traps even against huge monsters",
        "Hunters can loose several arrows almost simultaneously",
        "Hunters have mastered a special shooting technique whose shots can knock an opponent back",
        "Hunters can teach their pet to attack, to protect its master, and even to provoke the enemy",
        "Hunters know the habits of beasts so well that they can predict their attack in advance",
        "Hunters can pass through a forest without leaving behind a single noticeable trace",
        "Hunters can spot a creature that others don't even see",
    ],
    'Priest': [
        "Priests can heal several gravely wounded people at once",
        "Priests can place a magical shield around an ally that absorbs the next blow",
        "Priests can lift a curse from a friend or cure them of poison",
        "Priests can bring back to life a person who has just died",
        "A priest's power of the Light can be so great that it can burn the undead",
        "Priests can keep a comrade alive even when that comrade is barely able to fight anymore",
        "Priests can strengthen the will of an entire group of people with a single prayer",
        "Priests can instantly move to an ally who has found themselves in danger",
        "Priests can see a strength in a person that the person doesn't yet suspect they have",
        "Some priests have learned to draw power directly from the Void... but this priest isn't like that",
        "Some priests use the Void to drive an enemy mad... but this priest wouldn't do that",
        "The most dangerous priests can hear the whisper of the Void where others hear only silence... but this priest doesn't use such dark practices",
    ],
    'Warlock': [
        "Warlocks can summon a demon and make it fight on their side",
        "Warlocks can summon several demons, each of which has completely different abilities",
        "Warlocks can turn their own life force into magical energy",
        "Warlocks know how to curse an enemy so that the enemy gradually loses strength and begins to slowly die",
        "Warlocks can steal an opponent's life force and use it to restore their own health",
        "Warlocks can create stones that allow a fallen comrade to be brought back to life",
        "Warlocks can summon other people directly to themselves through a demonic portal",
        "Warlocks possess a dangerous ritual that lets several warlocks combine their powers and summon an especially powerful demon",
        "Warlocks can make a demon take a blow in their place",
        "Warlocks use soul shards as a source of magical power",
        "Warlocks can transform into demonic forms",
        "Warlocks study demons for so long that they can tell from a single word exactly what kind of creature they are dealing with",
    ],
    'Druid': [
        "Druids can turn into a huge bear and withstand a blow that would kill an ordinary warrior",
        "Druids can take the form of a huge cat and move completely silently",
        "Druids can turn into a cheetah and outrun even the fastest horses",
        "Druids can take the form of a fish and travel underwater without needing to breathe",
        "Druids can turn into a bird and fly across huge distances",
        "Druids can heal a grave wound with the power of nature alone",
        "Druids can summon roots right out of the ground to hold a fleeing opponent",
        "Druids can call up an entire swarm of insects and send it at the enemy",
        "Druids can cure an ally of poison or disease without using any potions or medicines",
        "Druids can change forms so quickly that the opponent doesn't manage to understand who exactly they are fighting",
        "Druids can restore their own strength right in the middle of battle, gradually turning the wounds they have taken into new life",
        "Druids can bring a fallen comrade back to life by asking nature to return them",
        "Druids can travel the world with almost no need for ordinary means of transportation",
        "Druids can enter into such a deep bond with nature that even wild beasts don't see them as strangers",
        "Druids can sense approaching danger from changes in the behavior of animals and plants",
    ],
    'Rogue': [
        "Rogues can vanish right before your eyes",
        "Rogues can open almost any lock, if they have time and the right tools",
        "Rogues can take the purse from the belt of a person standing next to them, and that person won't notice a thing",
        "Rogues can sneak up behind an enemy so quietly that the enemy hears the blow before the footsteps",
        "Rogues use poisons that can slow, weaken, or instantly kill an opponent",
        "Rogues can disarm a trap without touching it",
        "Rogues can blind an opponent with a single movement and disappear while the opponent is trying to figure out what happened",
        "Rogues can stun an opponent with a single precise blow",
        "Rogues can use their surroundings better than any warrior",
        "Rogues are so skillful that they can open a locked chest without leaving a single scratch on the lock",
        "Rogues can tell what is inside someone else's purse by its weight",
        "The most dangerous rogues don't look dangerous at all",
    ],
    'Shaman': [
        "Shamans can call upon fire, water, earth, or air right in the middle of battle",
        "Shamans can speak with the spirits of their ancestors and receive advice from them",
        "Shamans can call down lightning with a single wave of the hand",
        "Shamans can set down a totem that will heal or protect everyone nearby",
        "Shamans possess the art of creating totems that can support friends or harm enemies",
        "Shamans can temporarily turn into a wolf and move with incredible speed",
        "Shamans can summon elementals to aid them",
        "Shamans can bring a fallen comrade back to life",
        "Shamans can sense an approaching storm before any cloud appears",
        "Shamans understand the elements so well that they can make an ally's weapon fill with fire or lightning",
        "They say the elements may refuse to help a shaman if the shaman stops respecting them, but this shaman isn't like that",
        "A shaman doesn't command the elements; a shaman knows how to persuade them to help",
    ],
    'Paladin': [
        "Paladins can heal a gravely wounded comrade right in the middle of battle",
        "Paladins believe in the Light so strongly that they can raise a fallen ally and bring them back to life",
        "Paladins are given a faithful steed by their order when they become strong enough",
        "Some paladins' armor shines so brightly that it is hard to remain in darkness near them",
        "Paladins can protect a comrade with a magical shield capable of withstanding a deadly blow",
        "Paladins can become practically invulnerable for a short time",
        "A paladin's presence can give courage to an entire group of fighters",
        "Paladins can fight and heal at the same time, not letting the enemy take advantage of their allies' weakness",
        "Paladins can cleanse an ally of poison, disease, or other harmful effects",
        "Paladins speak of sacred auras that a paladin can maintain around themselves, helping everyone nearby",
        "Paladins know the enemies of the Light so well that they can turn those enemies' own power against them",
        "A true paladin can be the last person standing between a monster and defenseless people, and not retreat",
    ],
}

_LOGANAAR = _t('Druid', 'Loganaar', 'Moonglade')
_TARSHAW = _t('Warrior', 'Tarshaw Jaggedscar', 'Razor Hill, Durotar')

CLASS_TRAINERS = {
    'Alliance': {
        'Human': [
            _t('Warrior', 'Lyria Du Lac', 'Goldshire, Elwynn Forest'),
            _t('Mage', 'Zaldimar Wefhellt', 'Goldshire, Elwynn Forest'),
            _t('Priest', 'Priestess Josetta', 'Goldshire, Elwynn Forest'),
            _t('Warlock', 'Maximillian Crowe', "the basement of the Lion's Pride Inn, Goldshire"),
            _LOGANAAR,
            _t('Rogue', 'Keryn Sylvius', 'Goldshire, Elwynn Forest'),
            _t('Shaman', 'Tuluun', 'Azure Watch, Azuremyst Isle'),
            _t('Paladin', 'Brother Wilhelm', 'Goldshire, Elwynn Forest'),
        ],
        'Dwarf': [
            _t('Warrior', 'Granis Swiftaxe', 'the Thunderbrew Distillery, Kharanos, Dun Morogh'),
            _t('Hunter', 'Grif Wildheart', 'Kharanos, Dun Morogh'),
            _t('Priest', 'Maxan Anvol', 'Kharanos, Dun Morogh'),
            _t('Druid', 'Fylerian Nightwing', 'the Cenarion Enclave in Darnassus'),
            _t('Rogue', 'Hogral Bakkan', 'Kharanos, Dun Morogh'),
            _t('Shaman', 'Farseer Javad', 'Ironforge'),
            _t('Paladin', 'Azar Stronghammer', 'the Thunderbrew Distillery, Kharanos, Dun Morogh'),
        ],
        'Gnome': [
            _t('Warrior', 'Bilban Tosslespanner', 'the Hall of Arms in Ironforge'),
            _t('Mage', 'Magis Sparkmantle', 'Kharanos, Dun Morogh'),
            _t('Warlock', 'Gimrizz Shadowcog', 'Kharanos, Dun Morogh'),
            _t('Rogue', 'Fenthwick', 'the Forlorn Cavern in Ironforge'),
            _t('Shaman', 'Farseer Umbrua', 'the Valley of Heroes in Stormwind'),
        ],
        'Night Elf': [
            _t('Warrior', 'Kyra Windblade', 'Dolanaar, Teldrassil'),
            _t('Hunter', 'Dazalar', 'Dolanaar, Teldrassil'),
            _t('Priest', 'Laurna Morninglight', 'Dolanaar, Teldrassil'),
            _t('Druid', 'Kal', 'Dolanaar, Teldrassil'),
            _t('Rogue', 'Jannok Breezesong', 'Dolanaar, Teldrassil'),
            _t('Shaman', 'Sulaa', 'The Crystal Hall in the Exodar'),
        ],
        'Draenei': [
            _t('Warrior', 'Ahonan', "the Traders' Tier in the Exodar"),
            _t('Mage', 'Semid', 'Azure Watch, Azuremyst Isle'),
            _t('Hunter', 'Acteon', 'Azure Watch, Azuremyst Isle'),
            _t('Priest', 'Guvan', 'Azure Watch, Azuremyst Isle'),
            _t('Druid', 'Sheldras Moontree', 'the Park in Stormwind'),
            _t('Shaman', 'Gurrag', 'The Crystal Hall in the Exodar'),
            _t('Paladin', 'Tullas', 'Azure Watch, Azuremyst Isle'),
        ],
    },
    'Horde': {
        'Orc': [
            _TARSHAW,
            _t('Hunter', 'Harruk', 'Razor Hill, Durotar'),
            _t('Warlock', 'Dhugru Gorelust', 'Razor Hill, Durotar'),
            _LOGANAAR,
            _t('Rogue', 'Kaplak', 'Razor Hill, Durotar'),
            _t('Shaman', 'Swart', 'Razor Hill, Durotar'),
            _t('Paladin', 'Master Pyreanor', 'the Valley of Wisdom in Orgrimmar'),
        ],
        'Troll': [
            _TARSHAW,
            _t('Mage', "Un'Thuwa", "Sen'jin Village, Durotar"),
            _t('Hunter', "Jen'shan", 'the Valley of Trials, Durotar'),
            _t('Priest', "Tai'jin", 'Razor Hill, Durotar'),
            _t('Druid', 'Sheal Runetotem', 'the Elder Rise in Thunder Bluff'),
            _t('Rogue', 'Shenthul', 'the Cleft of Shadow in Orgrimmar'),
            _t('Shaman', "Sian'tsu", 'the Valley of Wisdom in Orgrimmar'),
        ],
        'Tauren': [
            _t('Warrior', 'Krang Stonehoof', 'Bloodhoof Village, Mulgore'),
            _t('Hunter', 'Thotar', 'Bloodhoof Village, Mulgore'),
            _t('Druid', 'Gennia Runetotem', 'Bloodhoof Village, Mulgore'),
            _t('Shaman', 'Narm Skychaser', 'Bloodhoof Village, Mulgore'),
            _t('Paladin', 'Osselan', 'the Hall of Blood in Silvermoon City'),
        ],
        'Undead': [
            _t('Warrior', 'Austil de Mon', "Gallows' End Tavern, Brill, Tirisfal Glades"),
            _t('Mage', 'Cain Firesong', "Gallows' End Tavern, Brill, Tirisfal Glades"),
            _t('Priest', 'Dark Cleric Beryl', "Gallows' End Tavern, Brill, Tirisfal Glades"),
            _t('Warlock', 'Rupert Boch', "Gallows' End Tavern, Brill, Tirisfal Glades"),
            _t('Druid', 'Turak Runetotem', 'Bloodhoof Village, Mulgore'),
            _t('Rogue', 'Marion Call', 'Brill, Tirisfal Glades'),
            _t('Paladin', 'Champion Cyssa Dawnrose', 'the Undercity'),
        ],
        'Blood Elf': [
            _t('Mage', 'Garridel', 'the Falconwing Inn, Falconwing Square, Eversong Woods'),
            _t('Hunter', 'Tana', "the Rangers' Lodge, Farstriders' Square, Silvermoon City"),
            _t('Priest', 'Belestra', 'the Court of the Sun in Silvermoon City'),
            _t('Warlock', 'Celoenus', 'the Falconwing Inn, Falconwing Square, Eversong Woods'),
            _t('Rogue', 'Elara', 'the Students of Shadow on Murder Row, Silvermoon City'),
            _t('Paladin', 'Ithelis', 'the Hall of Blood in Silvermoon City'),
        ],
    },
}
